services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.web

    container_name: web

    ports:
      - "8000:80"

    depends_on:
      - ai

  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile.ai

    container_name: focus-ai

    ports:
      - "8001:8000"

    devices:
      - "/dev/video0:/dev/video0"

    volumes:
      - ./ai:/app

    privileged: true
