services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.web

    container_name: web

    ports:
      - "80:80"

  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile.ai

    container_name: focus-ai

    expose:
      - "8000"
