FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    flask \
    pymysql \
    cryptography \
    opencv-python-headless \
    ultralytics \
    numpy \
    mediapipe
RUN mkdir -p /tmp/matplotlib && chmod 777 /tmp/matplotlib

ENV MPLCONFIGDIR=/tmp/matplotlib


COPY . .

CMD ["python", "start.py"]
