name: Capstone CI

on:
  push:
    branches:
      - dev

jobs:
  docker-compose-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker Compose Build
        run: docker compose -f compose.yml build
