FROM python:3.11

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && apt-get clean

RUN pip install fastapi uvicorn \
    opencv-python \
    ultralytics \
    boto3 \
    AWSIoTPythonSDK \
    numpy \
    mediapipe


COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
